feat(lesson): add schema for lesson
learnery-engine/api.creator.learnery pull request #48
Opened 2023-08-22 07:39 UTC by aldoprogrammer

## Related Issue(s)

[//]:
  #
  "[Cite any related issue(s) or feature request(s) from the repository's issue tracker.]"

Fixes # For #

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## API Changes documentation

```shell

```

```shell

```

## To-Do

- [ ]

## Additional Information

2023-08-22 18:55 UTC, Nasfame requested changes

2023-08-22 18:55 UTC, Nasfame commented on prisma/schema.prisma
> +  topics         Topic[]
Store a string of an array of topics is not a good reason for creating a nwe collection

Comment this now, and reference this to create graphql types. 

i think its best 

schema Json @db.JsonArray //

2023-08-23 00:19 UTC, aldoprogrammer commented on prisma/schema.prisma
> +  topics         Topic[]
```
model Section {
  id             String     @id @default(auto()) @map("_id") @db.ObjectId
  title          String
  courseId       String     @db.ObjectId
  course         Lesson     @relation(fields: [courseId], references: [id])
  topics         Json[]     @db.JsonArray
  @@map("sections")
}
```
I make it something like this, but it gives me error `Native type JsonArray is not supported for mongodb connector` And for my last coding which I store it as a string I follow this [docs ](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-scalar-lists-arrays)from Prisma official website.

2023-08-23 02:05 UTC, Nasfame approved these changes

2023-08-23 02:05 UTC, Nasfame commented on prisma/schema.prisma
> +}
Made in manually

2023-08-23 02:06 UTC, Nasfame approved these changes

2023-08-23 02:23 UTC, Nasfame commented on prisma/schema.prisma
> +  topics         Topic[]
done

2023-08-23 02:30 UTC, Nasfame commented on .env.example
done

2023-08-23 02:31 UTC, merged